import React from 'react';
import {View, StyleSheet, ScrollView} from 'react-native';
import {connect} from 'react-redux';
import {Text} from 'react-native-elements';

const FaqScreen = ({navigation, route, myWallets, current}) => {
  return (
    <ScrollView style={styles.container}>
      <View style={{margin: 20}}>
        <Text style={{fontWeight: '700', fontSize: 20}}>
          What is recovery phrase?
        </Text>
        <Text>
          The Secret 12-word Recovery phrase is the master key generated by your
          wallet. These words help you recover your funds in case your phone
          crashes or anything else happens which prevents you from accessing
          your wallet on the phone it is installed on.
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
});

const mapStateToProps = state => ({
  myWallets: state.wallet.myWallets,
  current: state.wallet.current,
});

const mapDispatchToProps = {};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(FaqScreen);
